#!/bin/sh
# this script is to send audit command

CEPEXEC="/sn/cr/cepexec"
rctbl="SERVER_IMOM"
rcfield="Server_IMOM_Access_Key"
spaname=`psql -Uscncraft -At -c "select span from spm_tbl where span like 'EPPSA%'"`

if [ -z "$spaname" ]
then
	echo "EPPSA SPA is NOT in IS state"
	exit 1
fi

sqltbl=`grep $rctbl /sn/sps/$spaname/$spaname.sym | awk -F\; '{print $1}'`
sqlfield=`grep $rcfield /sn/sps/$spaname/$spaname.sym | awk -F\; '{print $3}'`
rk=`psql -Uscncraft -At -c "select $sqlfield from $sqltbl"`

cmd="snd:text=\"alw:prepaid,audit=card\",RK=\"$rk\""
echo $cmd
$CEPEXEC SEND_TEXT "$cmd"
rc=$?
echo "send result is $rc"
