#!/bin/sh
# this script is to send CCRi, CCRu, CCRt in one command
interval=5

ccri
sleep $interval

ccru
sleep $interval

ccrt
echo "sleep $interval seconds after ccrt"
sleep $interval

pkill -u $(whoami) tailer
