#!/bin/sh

CCR_INDEX=SMS
CEPEXEC="/sn/cr/cepexec"
BASEFRM="/tmp/sms.frm"
CC_NUM=1
CC_NUM_COUNTER="/tmp/CC_NUM_COUNTER"
$CEPEXEC RCV_TEXT "RCV:TEXT,SPA" < $BASEFRM
$CEPEXEC SEND_TEXT "snd:text=\"CCR:$CCR_INDEX\",RK=\"diam_key\""
echo -e "\nSend CCR:$CCR_INDEX\n"
