#!/bin/sh
###########################################################
# name: ccre
# usage: ccre
# description:
#       this script is for user to send CCR for SMS call in 
#	terminal by command, no need copy cep cmd to subshl
#       before using this script, need:
#       1) update CCR_INDEX to the CCRi index you are using
#       2) update DIAMCL version and table name in sms.frm
#       3) update RK here to the rk you are using in DIAMCL
#
# author: Liu Hongwei
#         hong_wei.hl.liu@alcatel-lucent.com
###########################################################

CCR_INDEX=SMS
CEPEXEC="/sn/cr/cepexec"
BASEFRM="/u/ainet/hongwehl/bin/sms.frm"
CC_NUM=1
CC_NUM_COUNTER="/tmp/CC_NUM_COUNTER"
$CEPEXEC RCV_TEXT "RCV:TEXT,SPA" < $BASEFRM
$CEPEXEC SEND_TEXT "snd:text=\"CCR:$CCR_INDEX\",RK=\"diam_key\""
echo -e "\nSend CCR:$CCR_INDEX\n"
