#!/bin/sh

CCR_INDEX=UK01
CEPEXEC="/sn/cr/cepexec"
CC_NUM=1
CC_NUM_COUNTER="/tmp/PS_CC_NUM_COUNTER"
BASEFRM="/u/ainet/hongwehl/bin/ps.frm"

#if [ -f $CC_NUM_COUNTER ]
#then
#	mv $CC_NUM_COUNTER $CC_NUM_COUNTER.old
#fi

$CEPEXEC RCV_TEXT "RCV:TEXT,SPA" < $BASEFRM
$CEPEXEC SEND_TEXT "snd:text=\"CCR:$CCR_INDEX\",RK=\"diam_key\""
echo -e "\nSend CCRi, cc_request_number = $CC_NUM\n"

CC_NUM=$(($CC_NUM + 1))
echo $CC_NUM > $CC_NUM_COUNTER
