#!/bin/sh
###########################################################
# name: ccri
# usage: ccri
# description:
#	this script is for user to send CCRi in terminal by 
#	command, no need copy cep cmd to subshl
#	before using this script, need:
#	1) update CCR_INDEX to the CCRi index you are using
#	2) update DIAMCL version and table name in ps.frm
#	3) update RK here to the rk you are using in DIAMCL
# author: Liu Hongwei
#	  hong_wei.hl.liu@alcatel-lucent.com
###########################################################

CCR_INDEX=11
CEPEXEC="/sn/cr/cepexec"
CC_NUM=1
CC_NUM_COUNTER="/tmp/PS_CC_NUM_COUNTER"
BASEFRM="/u/ainet/hongwehl/bin/ps.frm"

#if [ -f $CC_NUM_COUNTER ]
#then
#	mv $CC_NUM_COUNTER $CC_NUM_COUNTER.old
#fi

$CEPEXEC RCV_TEXT "RCV:TEXT,SPA" < $BASEFRM
$CEPEXEC SEND_TEXT "snd:text=\"CCR:$CCR_INDEX\",RK=\"diam_key\""
echo -e "\nSend CCRi, cc_request_number = $CC_NUM\n"

CC_NUM=$(($CC_NUM + 1))
echo $CC_NUM > $CC_NUM_COUNTER
