#!/bin/sh
###########################################################
# name: ccrt
# usage: ccrt
# description:
#       this script is for user to send CCRt in terminal by 
#       command, no need copy cep cmd to subshl,
#
#       before using this script, need:
#       1) update CCR_INDEX to the CCRt index you are using
#       2) update DIAMCL version, table name in ps.frm and here
#       3) update RK here to the rk you are using in DIAMCL
#
# author: Liu Hongwei
#         hong_wei.hl.liu@alcatel-lucent.com
###########################################################

CCR_INDEX=UK03
CC_NUM_COUNTER="/tmp/PS_CC_NUM_COUNTER"
CC_NUM_FRM="/tmp/ps_cc_num.frm"
BASEFRM="/u/ainet/hongwehl/bin/ps.frm"
CEPEXEC="/sn/cr/cepexec"

if [ ! -f $CC_NUM_COUNTER ] 
then
	echo "There is no $CC_NUM_COUNTER, please run ccri first!\n"
	exit 1
fi

$CEPEXEC RCV_TEXT "RCV:TEXT,SPA" < $BASEFRM

read CC_NUM <$CC_NUM_COUNTER

echo "FORM=SPA_DIAMCL29B_7&CHG,index=\"$CCR_INDEX\",CCR_CC_Request_Number=\"$CC_NUM\",CHG!" > $CC_NUM_FRM
$CEPEXEC RCV_TEXT "RCV:TEXT,SPA" < $CC_NUM_FRM
$CEPEXEC SEND_TEXT "snd:text=\"CCR:$CCR_INDEX\",RK=\"diam_key\""
echo -e "\nSend CCRt, cc_request_number = $CC_NUM\n"

rm $CC_NUM_COUNTER
