#!/bin/sh

tempbpfile=/tmp/printcip.bp
tempsubshl=/tmp/printcip.subshl

spaname=`psql -Uscncraft -At -c "select span from spm_tbl where span like 'EPAY%'"`
if [ -z $spaname ]
then
	echo "EPAY is not IS, exit"
	exit 1
fi

cat <<!eof >$tempbpfile
print(Glb_FG_UBD_Bucket_Info_tbl[])
print(Glb_Group_Timer_Instance_Mapping_tbl[])
print(LDAP_Calls_In_Progress_tbl[])
print(Calls_In_Progress_Counters_tbl[])
print(Extend_CIPC_tbl[])
print(Bundle_PTP_CIP_tbl[])
print(Sync_In_Progress_tbl[])
detach
!eof

cat <<!eof>$tempsubshl
debug:spa=$spaname,client=all,source="$tempbpfile",ucl
!eof

subshl -F $tempsubshl 2>/dev/null
rm $tempbpfile $tempsubshl
