#!/bin/sh
enwtpps=`psql -Uscncraft -At -c "select version_name from sa_name_map where spa_base='ENWTPPS'"`
fc=`grep "^SPA_.*Feature_Configuration_tbl$" /sn/sps/$enwtpps/$enwtpps.sym |awk -F\; '{print $1}'`
cus_id=`grep "Feature_Configuration_tbl.*Customer_Identifier" /sn/sps/$enwtpps/$enwtpps.sym | awk -F\; '{print $3}'`

psql -Uscncraft -At -c "select $cus_id from $fc"
