#!/bin/sh

# usage: 
#	gdiamfrm <diamcl spa name>
#
# description: 
#	gen frm for diameter related call type, such ps, ngin and sms
#
# author: 
#	Liu Hongwei
#

if [ $# = 0 ]
then
	echo "usage: gdfrm <diamcl>"
	exit 1
fi

BASEBINDIR="/u/ainet/hongwehl/bin"
SMSFRM="$BASEBINDIR/sms.frm"
PSFRM="$BASEBINDIR/ps.frm"
NGINFRM="$BASEBINDIR/ngin.frm"
DIAMBASEFRM="$BASEBINDIR/diambase.frm"

diamcl=$1
if [ ! -d "/sn/sps/$diamcl" ]
then
	echo "$diamcl is not installed"
	exit 1
fi

diamsymfile=/sn/sps/$diamcl/$diamcl.sym
globalrc=`egrep "client global;rc$" $diamsymfile | awk -F\; '{print $1}'`
diam_tbl=`egrep "CCR_Message_Variable_Tbl$" $diamsymfile | awk -F\; '{print $1}'`
diam_sub_id=`egrep "CCR_Subscription_Id_Tbl$" $diamsymfile | awk -F\; '{print $1}'`
diamcl_fsm_tbl=`psql -Uscncraft -At -c "select item from rcmenutbl where title like 'client fsm Diameter_Peer_FSM' and parent='$diamcl'"`
diamcl_fsm_rk=`grep diam_client_access $diamsymfile | awk -F\; '{print $3}'`
diamcl_fsm_seq=`psql -Uscncraft -At -c "select seq from $diamcl_fsm_tbl where $diamcl_fsm_rk='diam_key' limit 1"`

version=`psql -Uscncraft -At -c "select version_name from SA_NAME_MAP where spa_base='ENWTPPS'" | sed "s,ENWTPPS,,g"`
new_da="false"
ret=`expr match $version "[0-9][0-9]*$"`
if [ $ret -gt 0 ]
then
    if [ $version -ge 183 ]
    then
        new_da="true"
    fi
fi
#echo version is $version
epayname=EPAY$version
epaysymfile=/sn/sps/$epayname/$epayname.sym
da_tbl=`egrep "Diameter_Authorization_tbl$" $epaysymfile | awk -F\; '{print $1}'`
epay_diam_fsm_tbl=`psql -Uscncraft -At -c "select item from rcmenutbl where title like 'client fsm Diameter_PROT_FSM%' and parent='$epayname'"`
epay_diam_fsm_seq=`psql -Uscncraft -At -c "select seq from $epay_diam_fsm_tbl limit 1"`

>$DIAMBASEFRM
isDAExist=`psql -Uscncraft -At -c "select count(*) from $da_tbl where INDX_1='DIAMCL'"`

if [ $isDAExist -eq 0 ]
then
        if [ $new_da = "false" ]
        then
	    cat <<!eof >$DIAMBASEFRM
FORM=$da_tbl&NEW,index.Diameter_Client_Identifier="DIAMCL",index.Application_ID="4",Diameter_Client_Service_ID="375",Diameter_Client_Service_Support="Y",Service_Context_ID="version2.clci.ipc@vodafone.com",NEW!
!eof
        else
	    cat <<!eof >$DIAMBASEFRM
FORM=$da_tbl&NEW,index.Diameter_Client_Identifier="DIAMCL",index.Application_ID="4",index.Diameter_Client_Identifier_1=";",index.Diameter_Client_Identifier_2=";",index.Diameter_Client_Identifier_3=";",Diameter_Client_Service_ID="1",Diameter_Client_Service_Support="Y",Service_Context_ID="6.32251@3gpp.org",Delimeter=";",Flexible_Session_ID="N",New_Format="3:1:2",Partition_Length_Value="L10:L10:L2",NEW!
!eof
        fi
fi

if [ ! -z "$diamcl_fsm_seq" ]
then
	cat <<!eof >>$DIAMBASEFRM
FORM=$diamcl_fsm_tbl&CHG,sequence="$diamcl_fsm_seq",GETDATA,Routing_String_SSN.routing_string="DM4S317",Routing_String_SSN.internal_ssn="317",CHG!
!eof
fi

if [ ! -z "$epay_diam_fsm_seq" ]
then
	cat <<!eof >>$DIAMBASEFRM
FORM=$epay_diam_fsm_tbl&CHG,sequence="$epay_diam_fsm_seq",GETDATA,Routing_String_SSN.routing_string="DM4",Routing_String_SSN.internal_ssn="318",CHG!
!eof
fi
#/cs/sn/cr/cepexec RCV_TEXT "RCV:TEXT,SPA" <$DIAMBASEFRM

if [ $new_da = "false" ]
then
    cat <<!eof >$SMSFRM
FORM=$da_tbl&CHG,index.Diameter_Client_Identifier="DIAMCL",index.Application_ID="4",Service_Context_ID="32274@3gpp.org",CHG!
!eof

    cat <<!eof >$PSFRM
FORM=$da_tbl&CHG,index.Diameter_Client_Identifier="DIAMCL",index.Application_ID="4",Service_Context_ID="version2.clci.ipc@vodafone.com",CHG!
!eof

    cat <<!eof >$NGINFRM
FORM=$da_tbl&CHG,index.Diameter_Client_Identifier="DIAMCL",index.Application_ID="4",Service_Context_ID="version1.nginas.32260@3gpp.org",CHG!
!eof

else
    cat <<!eof >$SMSFRM
FORM=$da_tbl&CHG,index.Diameter_Client_Identifier="DIAMCL",index.Application_ID="4",index.Diameter_Client_Identifier_1=";",index.Diameter_Client_Identifier_2=";",index.Diameter_Client_Identifier_3=";",Service_Context_ID="32274@3gpp.org",CHG!
!eof

    cat <<!eof >$PSFRM
FORM=$da_tbl&CHG,index.Diameter_Client_Identifier="DIAMCL",index.Application_ID="4",index.Diameter_Client_Identifier_1=";",index.Diameter_Client_Identifier_2=";",index.Diameter_Client_Identifier_3=";",Service_Context_ID="version2.clci.ipc@vodafone.com",CHG!
!eof

    cat <<!eof >$NGINFRM
FORM=$da_tbl&CHG,index.Diameter_Client_Identifier="DIAMCL",index.Application_ID="4",index.Diameter_Client_Identifier_1=";",index.Diameter_Client_Identifier_2=";",index.Diameter_Client_Identifier_3=";",Service_Context_ID="version1.nginas.32260@3gpp.org",CHG!
!eof
fi

for ccr in ccru ccrt nginu ngint
do
	script=$BASEBINDIR/$ccr
	if [ -f "$script" ]
	then
		olddiam_tbl=`egrep FORM=SPA_DIAM $script | awk -F\& '{print $1}' | awk -F= '{print $2}'`
		sed -i "s,$olddiam_tbl,$diam_tbl,g" $script
	fi
done
