#!/bin/sh

# usage: 
#	gdiamfrm <diamcl spa name>
#
# description: 
#	gen frm for diameter related call type, such ps, ngin and sms
#
# author: 
#	Liu Hongwei
#

if [ $# = 0 ]
then
	echo "usage: gdfrm <diamcl>"
	exit 1
fi

BASEBINDIR="/u/ainet/hongwehl/bin"
SMSFRM="$BASEBINDIR/sms.frm"
PSFRM="$BASEBINDIR/ps.frm"
NGINFRM="$BASEBINDIR/ngin.frm"

diamcl=$1
if [ ! -d "/sn/sps/$diamcl" ]
then
	echo "$diamcl is not installed"
	exit 1
fi

symfile=/sn/sps/$diamcl/$diamcl.sym
globalrc=`egrep "client global;rc$" $symfile | awk -F\; '{print $1}'`
diam_tbl=`egrep "CCR_Message_Variable_Tbl$" $symfile | awk -F\; '{print $1}'`


version=`psql -Uscncraft -At -c "select version_name from SA_NAME_MAP where spa_base='ENWTPPS'" | sed "s,ENWTPPS,,g"`
#echo version is $version
epayname=EPAY$version
symfile=/sn/sps/$epayname/$epayname.sym
da_tbl=`egrep "Diameter_Authorization_tbl$" $symfile | awk -F\; '{print $1}'`

cat <<!eof >$SMSFRM
FORM=$globalrc&CHG,Diameter_AVP_Bound_Enum="diameter_vsabe_3gpp_ro",CHG!
FORM=$da_tbl&CHG,index.Diameter_Client_Identifier="DIAMCL",index.Application_ID="4",Service_Context_ID="32274@3gpp.org",CHG!
!eof

cat <<!eof >$PSFRM
FORM=$globalrc&CHG,Diameter_AVP_Bound_Enum="diameter_vsabe_vodafone_version_2",CHG!
FORM=$da_tbl&CHG,index.Diameter_Client_Identifier="DIAMCL",index.Application_ID="4",Service_Context_ID="version2.clci.ipc@vodafone.com",CHG!
!eof

cat <<!eof >$NGINFRM
FORM=$globalrc&CHG,Diameter_AVP_Bound_Enum="diameter_vsabe_3gpp_ro",CHG!
FORM=$da_tbl&CHG,index.Diameter_Client_Identifier="DIAMCL",index.Application_ID="4",Service_Context_ID="version1.nginas.32260@3gpp.org",CHG!
!eof

for ccr in ccru ccrt nginu ngint
do
	script=$BASEBINDIR/$ccr
	if [ -f "$script" ]
	then
		olddiam_tbl=`egrep FORM=SPA_DIAM $script | awk -F\& '{print $1}' | awk -F= '{print $2}'`
		sed -i "s,$olddiam_tbl,$diam_tbl,g" $script
	fi
done
