#!/usr/bin/perl 
# generate breakpoint file
# based: tliu002 2009/04/25 16:45:18 <Tao.Liu@alcatel-lucent.com>
# enhanced: xiangdzh 2012/03/29 <Xiangdong.Zhou@alcatel-lucent.com>
# minimum fix just for error elimination and progressbar enhanced: jinglonz 2017/02/17 <Jinglong.zhao@alcatel-lucent.com>

# import
use File::Spec;
use File::Basename;
use Cwd;
# use strict 'vars';

#showing the progress, 10,000 lines incr one grid
use constant MAX_Grid   => 50;    # i think the lines number < 130w lines
use constant Const_Grid => 50;
our $cur_pro_num = 0;
our $OneGrid = Const_Grid / MAX_Grid;

# hash table definition
our %config = (
	"level"		=> 1,
	"file"		=> "spa.bp"
);
our %scope = (
	"fsm"			=> "default",
	"state"			=> "default",
	"event"			=> "default",
	"def_function"	=> "default"
);
our %mark = (
	"table"		=> "===>",
	"function"	=> "===>function:",
	"return"	=> "===>"
);
our %skip = (
	"default default Svr_Set_Subtrace" => 1,
	"default default Debug_Info_Func" => 1,
	"default default Set_Call_Dynamic_Flag" => 1,
	"default default Get_Call_Dynamic_Flag" => 1,
	"default default Set_Call_Dynamic_String" => 1,
	"default default Get_Call_Dynamic_String" => 1,
	"default default Set_Call_Dynamic_Counter" => 1,
	"default default Get_Call_Dynamic_Counter" => 1,
	"default default Set_Call_Dynamic_Long_Counter" => 1,
	"default default Get_Call_Dynamic_Long_Counter" => 1,
	"default default Set_Call_Dynamic_Float" => 1,
	"default default Get_Call_Dynamic_Float" => 1
);

our %GlobalVarValue = (
	"Glb_DEBUG_LEVEL" => 9,
	"Glb_Cache_Table_Clear_Interval" => 3600,
	"Glb_Service_Measurement_Interval" => 3600,
	"Glb_Service_Meas_Interval" => 3600,
	"Glb_FGC_Check_Queue_Delay" => 10000,
	"Glb_Check_Permanent_Instance_Interval" => 1000000
);
our %GlobalVarTitle = (
	"Glb_Cache_Table_Clear_Interval" => "Do you want generate following BP to disable Cache_Table_Clear?",
	"Glb_Service_Measurement_Interval" => "Do you want generate following BP to disable flood service measurement log?",
	"Glb_Service_Meas_Interval" => "Do you want generate following BP to disable EPPSA flood service measurement log?",
	"Glb_FGC_Check_Queue_Delay" => "Do you want generate following BP to disable flood output?",
	"Glb_Check_Permanent_Instance_Interval" => "Do you want generate following BP to disable Check_Permanent_Instance?"
);
our %GlobalVarOpen = (
	"Glb_DEBUG_LEVEL" => 1,
	"Glb_Cache_Table_Clear_Interval" => -1,
	"Glb_Service_Measurement_Interval" => -1,
	"Glb_Service_Meas_Interval" => -1,
	"Glb_FGC_Check_Queue_Delay" => -1,
	"Glb_Check_Permanent_Instance_Interval" => -1
);
our @GlobalVar = ("Glb_DEBUG_LEVEL", "Glb_Service_Measurement_Interval", "Glb_Service_Meas_Interval", "Glb_Cache_Table_Clear_Interval", "Glb_FGC_Check_Queue_Delay", "Glb_Check_Permanent_Instance_Interval");
our @EPAYGlbVar = ("Glb_Service_Measurement_Interval", "Glb_Cache_Table_Clear_Interval");
our @EPPSAGlbVar = ("Glb_Service_Measurement_Interval", "Glb_Service_Meas_Interval", "Glb_FGC_Check_Queue_Delay", "Glb_Check_Permanent_Instance_Interval");
our @ALL_BP = ();
our @CodePoint = (1);
our @FSM_CodePoint = (1);
our $func_name = "";
our %args = @ARGV;
our $Inputfile = "";
our $MYNODE    = $ENV{MYNODE};
our $Is_EPAY = 0;
our $BP_LVL = 0;
our $BP_Level = 0;
our $BP_F = "";
our $BP_File = "";

# Regex
our $Match_2Brack_PATTERN = '\(((\([^\(\)]*\)|[^\(\)]*)*)\)';
our $Function_TYPE_PATTERN = '(def_function)\s*([a-zA-Z0-9_!]*)\s*'.$Match_2Brack_PATTERN;
our $Match_1Brack_PATTERN = '\(([^\(\)]*)\)';
our $Table_TYPE_PATTERN = '(element_exists|best_match|prefix_matches)\s*'.$Match_1Brack_PATTERN;
our $IgnoreFunction =
	'get_spa_process_status|clock|LDAP_Check_Account_Expiration|printable_hex_to_raw_string|counter|power|ftoi|element_exists';
our $IgnoreSLLFunction = 
	'Get_Day_ID|UnixTime_To_Date_TimeZone|Calculate_End_Date|Insert_Annc|map|Calculate_First_Day_Current_Period|Get_Call_Dynamic_Counter|Get_Call_Dynamic_Flag|Get_Call_Dynamic_String|Get_Call_Dynamic_Long_Counter|Get_Call_Dynamic_Float|Convert_Value_To_Text_String|Get_Total_Reserved_Bucket|Get_Total_Captured_Bucket|Get_Total_Refunded_Bucket|Parser_URL_Format|Diam_COSP_Exists_In_ExtCOSP|Need_Determine_Zone|Date_Format_Conversion|Fill_Text_Format|Get_Long_Length_Value_From_EPM|Process_PP|Process_Dot_To_Comma|find|Check_Lmt_VoLTE_On_No_DiamAllowed|Check_Applied_UBD_Counter|ALCC_Compare_Credit_With_Trigger|Compress_One_Digit_And_Filler|Get_No_Counting_Timestamp_From_Prom_Info';
our $ignoreTable =
	'Local_Reset_Discount_Info_tbl|L_Diam_BOU_Index_tbl|L_SPI_UC_Cross_tbl|L_SPI_Ro_Info_tbl|L_SPI_PC_Related_Grp_Bkt_tbl';
# Some built-in functions can be evaluated in return statement BP
our $BuiltinFunc = 'client_cc_enum|substring|string|bit!or|any|bit!is_set|length|hex_value|counter_to_hex';
# Skip_FSM_List is for performance issue, 
our $Skip_FSM_List = 'INTER_ECS_FSM';

# common function
sub usage {
	my $pstr = <<EOF
Usage:	genbpN [-f src_file] [-l bp_level] [-o bpfile]
	genbpN [-spa spa_name] [-l bp_level] [-o bpfile]
	genbpN [-h]	look for this help
	
	parameters:
	src_file	target spa source file name, eg. EPAY274.src
	spa_name	target spa name, eg. EPAY274
	bp_level	1~3, different details in breakpoints, Default Value: 1
			1) only generate table search, eg. element_exists, prefix_matches, best_match
			2) including (1), more generate function invoke bp, eg. def_function, subrouting
			3) including (2), more generate function return bp, eg. return
			*) more than 3, will be think as 3, less than 1 will be think as 1
	bpfile		bp file name will be generated, if not provisioned, bpfile name will be "spa.bp"
EOF
      ;
    print $pstr;
    exit 0;
}

sub p_error {
    print @_;
    usage;
}

sub incr_progress {
	my ($process) = @_;

	$t_t = $process;

    print "\r", 'Parsed: [', '=' x $t_t, ( " " x ( Const_Grid - $t_t ) ), '] ';
    printf( "%.0f %", $t_t / MAX_Grid * 100);
}

FILE;
OUTPUT;
sub openFile {
	my ($file, $bp) = @_;

	unless(open(FILE, "$file")) {
		print "can not open $file";
		return -1;
	}
	
	unless(open(OUTPUT, $bp)) {
		print "can not open $bp";
		return -1;
	}
	
	return 0;
}

sub closeFile {
	close(FILE);
	close(OUTPUT);
}

sub comments {
	my ($line) = @_;

	if ($line =~ /^\s*(#.*)?$/o) {
		return 1;
	} else {
		return 0;
	}
}

sub escape {
	my $line = "";	
	while (<FILE>) {
		#checkLineNo();
		$line = $_;
		if ($line =~ /^\s*%\}/o) {
			return 0;
		}
	}

	return -1;
}

sub dynamic {
	my $line = "";
	while (<FILE>) {
		#checkLineNo();
		$line = $_;
		if ($line =~ /^version\s*\"([a-zA-Z]+)/oi) {
			judge_Src_Type($1);
		}
		if ($line =~ /^\s*end\s+dynamic/o) {
			return 0;
		}
	}

	return -1;
}

sub subroutine {
	my ($name, $str) = @_;
	my $line = "";
	my $linenum = 0;

	while(<FILE>) {
		#checkLineNo();
		$line = $_;
		if ($line =~ /^\s*end\s+subroutine/o) {
			return 0;
		}
	}
	
	return 0;
}

sub generateLineBp {
	
}

sub generateBp {
	my ($linenum, $context) = @_;
	
	my $pr_str = "at $linenum \nprint(\n$context\n) \nend at \n";
	push(@ALL_BP, $pr_str);
}

#bugfix for debug error, Promo_Prio_Map_tbl does not have a default index.
#bugfix for log error, there is no record at 'Counter_Notification_Info_tbl[0].
our %skip_tbl_key_pair = (
	'Promo_Prio_Map_tbl' => 'L_Prom_Usage_Info_Tbl\.Product_Type|Local_Prom_Usg_Info_Tbl\.Product_Type|Local_Prom_Usage_Info_Tbl\.Product_Type',
	'Discount_Definition_tbl' => 'Counter_Notification_Info_tbl\.DID',
	'Glb_Diameter_Session_DB_tbl' => 'Diameter_Request\.Session_Tbl_Key'#,
	#'TCPIP_Server_Connection_tbl' => 'Multi_Grp_TCPIP_Queue_Tbl\.TCPIP_Message_Queue_Tbl_rec\.TCPIP_Message_Queue_Tbl\.Send_Client_ID'
);

our $explicit_indexed_tbl = '[\w]+\.[\w]+Tbl\.';#'Glb_Account_Ext_Cnt_Info_Tbl.DID_Ext_Rec\.DID_Ext_Tbl';

#support for function input parameters with modifier.
our $FunctionModifier = 'adaptable';

sub process_table_search {
    my ( $type, $params ) = @_;

    if ( $type =~ m/element_exists|best_match|prefix_matches/o ) {
        my @params_tmp = split( /,/, $params );

        if ( @params_tmp + 0 >= 2 ) {
            my $tb_name = $params_tmp[0];
            my $tb_indx = $params_tmp[1];

            #2011/08/18 fix, skip ignor table
        	return '' if $tb_indx =~ m/^\s*($ignoreTable)\./o;
           	    
            #2010/10/19 22:49:01 fix, skip element_exist with table.index as key
            return '' if $tb_indx =~ /\.index$/o;
			
			#2017/02/17 fix  skip special tbl_key_pair to omit debug error.
			my $ignorePair = $skip_tbl_key_pair{$tb_name};
			if ($ignorePair) {
				if($tb_indx =~ m/^\s*($ignorePair)/gi) {
					return '' ;
				}
			}
			#2018/04/19 skip explicit_indexed_tbl
			if ($tb_indx =~ m/\s*($explicit_indexed_tbl)/gi) {
				return '';
			}
            
            return '"' .$mark{"table"}." $tb_name" . ' key=",' . $tb_indx;
        }
    }
    return '';
}

sub process_function {
    my ($type, $name, $params) = @_;
    my $func_name = $name;
	my $tmp = "";
	my $tmp1 = "";
	my $idx = 0;

    trim_string($params);
    if ( $type =~ m/def_function/o ) {
		my @params_arr = split( /,/, $params );

		my @params_arr_tmp = ();
        for ( $idx = 0 ; $idx <= $#params_arr ; $idx++ ) {
			#remove pre modifier such as adaptable
			$params_arr[$idx] =~ s/^\s*($FunctionModifier)//g;
            $params_arr[$idx] =~ /^\s*([&]?[a-zA-Z0-9_!]*)(.*)$/o; #add reference pattern check 2017/04/12 by jinglonz
            my $tmp_param = $1;
            $tmp_param .= '[]' if ( $2 =~ /table$/oi or $2 =~ /table_type$/io );
            push( @params_arr_tmp, $tmp_param );
        }
        @params_arr = @params_arr_tmp;

        $tmp1 = "(\",\n";
        if ( $#params_arr >= 0 ) {
            for ( $idx = 0 ; $idx < $#params_arr ; $idx++ ) {
				next if ( $params_arr[$idx] =~ /^\s*&/io ); # leave reference para. un-processed at present 2017/04/13 by jinglonz
                $tmp1 =
                  "$tmp1\"$params_arr[$idx]=\",$params_arr[$idx],\",\",\n";
            }
            $tmp1 = "$tmp1\"$params_arr[$idx]=\",$params_arr[$idx],\n" if ( $params_arr[$idx] !~ /^\s*&/io ); # leave reference para. un-processed at present 2017/04/13 by jinglonz
        }
        $tmp1 = "$tmp1\")\"";
        $tmp  = "\"".$mark{"function"}." $func_name $tmp1";
        
        #Member_List is not a table, skip.
        return '' if $tmp =~ m/Member_List\[\]/o;
        return $tmp;
    }
    return '';
}


sub process_function_return {
    my ( $type, $params, $fun_name ) = @_;
    
    if ($BP_LVL >=3 && $type =~ /return/o ) {
        #special for SLL invoke function
        #return "\"".$mark{"return"}." $fun_name return: !shit,BP un-available here!\""
        return "\"".$mark{"return"}." $func_name return: BP un-available here!\""
            if $params =~ /$IgnoreSLLFunction/o;
        trim_string($params);
		#print $params."\n";
        $params =~ s/^\s*\((.*)\)/\1/g;

        #return '' if $params =~ /\(/o;

        #special for invoke builtin function
        #Note: for current, can not add built-in function into breakpoint, so ignore it
	my $para_temp = $params;
	$para_temp =~ s/\b($BuiltinFunc)\s*\(//g;
	if ($para_temp =~ /([a-zA-Z][!\w]*)\s*\(/o)
	{
		$params = '"BP_LIMIT: ' . $1 . '"';
	}

        my $ret_res = $params;
        #skip return with a expression
        return ''	if ($params =~ m/\/+/o);
	$ret_res = '"BP_Limit: Explicit indexed table"' if ($ret_res =~ m/\s*($explicit_indexed_tbl)/gi);
	#support return without meaningful feature
	$ret_res =~ s/^\s*$/\"BP_LIMIT: void\"/g;
	$ret_res =~ s/;//g;
	$ret_res =~ s/0\.0/0/g;
	$ret_res =~ s/^float\((.*)\)$/$1/gi;
        return "\"".$mark{'return'}." ".$func_name." return: \",$ret_res";
    }
    return '';
}

# conj many lines without '\n' and '#.*'
sub trim_string {
    my $str = \shift;
    if ( $$str =~ /^\s*#/o ) {
        $$str = '';
        return 1;
    }
    $$str =~ tr/\n//d;

    #$$str =~ s/^\s*|\s*$|[^"#]#+.*$//go;
    $$str =~ s/^\s*//go;
    $$str =~ s/([^"#])#+.*$/\1/go;

    return 1;
}

# is need more line
sub need_more_line {
    my ($in_str, $type ) = @_;
    my $num = 1;
    my $idx = index( $in_str, '(', 0 );

    return 0 if ( $idx < 0 );

    $idx += 1;
    my @tmp = split( //, $in_str );
    while ( $idx < length($in_str) && $num != 0 ) {
        if ( $tmp[$idx] eq '(' ) {
            $num++;
        }
        elsif ( $tmp[$idx] eq ')' ) {
            $num--;
        }
        $idx++;
    }
    if ( $num > 0 ) {
        return 1;
    }
    elsif ( $num == 0 ) {
        my $tmp_str = substr( $in_str, $idx );
        return 1 if $tmp_str =~ /^\s*$/o && $type == 1;
        return 0;
    }
    return 0;
}

sub Is_Brace_Match_B {
    my ($str) = @_;
	my $len = 0;

	while(1) {
		if ($str =~ /\(/o) {
			$str =~ s/\(//;
			$len ++;
		} elsif ($str =~ /\)/o) {
			$str =~ s/\)//;
			$len --;
		} else {
			last;
		}
	}
	
	if ($len == 0) {
		return 1;
	} else {
		return 0;
	}
}

sub Is_Brace_Match {
    my ($str) = @_;
    my $pos1 = 0;
    my $pos2 = length($str) - 1;
    while (1) {
        my $idx = index( $str, '(', $pos1 );
        my $ridx = rindex( $str, ')', $pos2 );
        if ( $idx >= 0 && $ridx >= 0 ) {
            $pos1 = $idx + 1;
            $pos2 = $ridx - 1;
        }
        elsif ( $idx < 0 && $ridx < 0 ) {
            return 1;
        }
        else {
            return 0;
        }
    }
}

#print Is_Brace_Match("return (substring(Input_String,1,2):")."\n";
#print Is_Brace_Match("return (substring(Input_String,1,2):substring(Input_String,4,2):")."\n";
#print Is_Brace_Match("return (substring(Input_String,1,2):substring(Input_String,4,2):substring(Input_String,7,2))")."\n";
#exit 0;

sub def_function {
	my ($name, $line) = @_;
	my $pr_str = "";
	my $execline = "";
	my $linenum = 0;
	my $fun_name = "";
	my $new_line = "";

	$func_name = $name;
	# check the function whether be skipped	
	if ($BP_LVL >= 2) {
		trim_string($line);
		
		#bug fix, def_function has no parameter and parens
		if ($line =~ /^\s*def_function\s*[\w!]+\s+[\w!]+/o) {
			$line =~ s/^(\s*def_function\s*[\w!]+\s*)/\1\(\)/g;
		}

        #for def_function, look for the first '('
        while ( $line !~ /\(/o ) {
        	#print "$new_line\n";
        	#checkLineNo();
            $new_line = <FILE>;
            trim_string($new_line);
            $line .= $new_line;
        }
		
		#get One Whole Line for function defination
		while ((need_more_line($line, 1) == 1) && ($new_line = <FILE>)) {
			#print $line."\n";
			#checkLineNo();
		    trim_string($new_line);
		    $line .= $new_line;
		}

		#print $line."\n";
		$line =~ m/$Function_TYPE_PATTERN/o;
		$fun_name = $2;
		my $param = $3;
		$pr_str = process_function($1, $2, $3);
		if ($pr_str eq '') {
			#my $linenum = $.;
			#print "[".$linenum."]get $fun_name parameters failed($param).\n";
			#exit 0;
			return -1;
		}
		
		# fetch the first executable line
		$execline = fetchFisrtExecLine ($line);
		$linenum = $.;
		generateBp($linenum, $pr_str);

		#2010/06/12 10:05:58 fix: if the 1st line is return, need generate function return bp for this line
		if( $BP_LVL >= 3 && $execline =~ /^\s*return(.*)$/o){
			parse_statement_return($1);
		}
	}
}

sub fetchFisrtExecLine {
	my ($line) = @_;
	my $new_line = "";
	
	if ( $line =~ /\s*dynamic\s*/o ) {
        while ( $new_line = <FILE> ) {
        	#checkLineNo();
            next if ( $new_line =~ /^\s*#|^\s*$/o );
            last if ( $new_line =~ /\s*end\s*dynamic/o );
        }

        while ( $new_line = <FILE> ) {
    	   	#checkLineNo();
    	   	last if ( $new_line !~ /^\s*#|^\s*$/o );
    	}

    } else {
        #look for the first executable line in function
        while ( $new_line = <FILE> ) {
        	#checkLineNo();
            last if ( $new_line !~ /^\s*#|^\s*$/o );
        }
        if ( $new_line =~ /^\s*dynamic/o ) {
            while ( $new_line = <FILE> ) {
            	#checkLineNo();
                next if ( $new_line =~ /^\s*#|^\s*$/o );
                last if ( $new_line =~ /\s*end\s*dynamic/o );
            }
            while ( $new_line = <FILE> ) {
    	    	#checkLineNo();
    	    	last if ( $new_line !~ /^\s*#|^\s*$/o );
    		}
        }
    }
    
    return $new_line;
}

# parsing
sub parsing {
	my $line = "";
	my $linenum = 0;
	my $prt_str = "";
	my $tmp = 0;
	my $fblock = ((stat(FILE))[7])/MAX_Grid; #set the progress block size.
	my $fratio = 1;
	my $cur_pro = 0; #current read position of the file.

	$| = 1;
	incr_progress(1);
	dynamic();
	while (<FILE>) {
		$line = $_;
		#checkLineNo();
		next		if (comments($line) == 1);

	    if ( $line =~ /^\s*escape\s*/o ) {
	    	escape();
	    	next;
	    }
		
	    $tmp ++;
	    if ( $tmp > 15000 ) {
	        $tmp = 0;
			$cur_pro = tell(FILE);
			$fratio = int($cur_pro/$fblock) if ($cur_pro != -1);
	        incr_progress($fratio);
	    }
		
		if ($line =~ /^\s*FSM\s+($Skip_FSM_List)\s+/oi) {
			genSkip_FSM_Line();
		}
		
		if ($line =~ /^\s*end\s+FSM\s+($Skip_FSM_List)\s+/oi) {
			genSkip_FSM_Line();
		}

		if ($line =~ /^\s*subroutine\s+([\w!]+)/o) {
			subroutine($1, $line);
			next;
		}

		if ($line =~ /^\s*(if|test|elif|while)[^\w_]/o) {
			# generate bp for table when met element_exist in switch
			parse_conditon_table($1, $line);

		} elsif ($line =~ /^\s*set\s+Glb_Best_Match\s*=/o) {
			# generate bp for table when met best_match in set
			parse_statement_table($line);

		} elsif ($line =~ /^\s*return(.*)$/o) {
			# generate bp for table when met best_match in set
			parse_statement_return($1);

		} elsif ($line =~ /^\s*(def_function|event|state|fsm)\s+([\w!]+)/o) {
			# set scope
			my $type = $1;
			my $name = $2;
			setScope($type, $name);
			def_function($name, $line)		if ($type eq "def_function");

		} elsif ($line =~ /^\s*end\s+(def_function|event|state|fsm)\b/o) {
			# reset scope
			resetScope($1);
		}
	}

	incr_progress(MAX_Grid);
	#print "well done.\n";
}

our $AMA_Tbl = 'AMA_Record_Generation_tbl';
sub parse_conditon_table {
	my ($key, $line) = @_;
	my $one_line_if_then = 0;
	my $new_line = "";
	my $linenum = $.;
	my $orglinenum = $linenum;

	trim_string($line);
	$one_line_if_then = 1 if $line =~ /\s+then/o;
	#get One Whole Line of if
	while ( ( $one_line_if_then == 0 ) && ( $new_line = <FILE> ) ) {
		#checkLineNo();
	    next if ( $new_line =~ /^\s*#|^\s*$/o );
	    last if ( $new_line =~ /^\s*(then|case|exit|do)/o );
	    trim_string($new_line);
	    $line = $line . $new_line;
	    $one_line_if_then = 1		if $line =~ /\s+then/o;
	}
	
	# bugfix for can not set bp on 'elif' line, set bp at next line.
	if($key eq 'elif' || $key eq 'if') {	
		# fetch the first executable line
		$new_line = fetchFisrtExecLine ($line);
		$linenum = $.;
		
		if ($new_line =~ /^\s*(if|test|while)[^\w_]/o) {
			# generate bp for table when met element_exist in switch
			parse_conditon_table($1, $new_line);
			
		} elsif ( $BP_LVL >= 3 && $new_line =~ /^\s*return(.*)$/o ) {
	        parse_statement_return($1);
			
	    } elsif ($new_line =~ /^\s*set\s+Glb_Best_Match\s*=/o) {
			# generate bp for table when met best_match in set
			parse_statement_table($new_line);

		} elsif ( $new_line =~ /^\s*(else|elif)/o) {
			# there is no executable line in if clause
			return 0;
		}
	}

	if ( $line =~ m/$Table_TYPE_PATTERN/o ) {
		# the AMA_Generation_tbl shoud be checked before if condition clause.
		my $type = $1, $params = $2;
		$linenum = $orglinenum if ( $params =~ /$AMA_Tbl/gi );
		my $ret_str = process_table_search( $type, $params );
		unless($ret_str eq '') {
			generateBp($linenum, $ret_str);
		}
	}

	return 0;
}

sub parse_statement_table {
	my ($line) = @_;
	my $linenum = $.;
	my $new_line = "";
	
	trim_string($line);
    #get One Whole Line of if
    while ( $new_line = <FILE> ) {
    	#checkLineNo();
        next if ( $new_line =~ /^\s*#|^\s*$/o );
        last if ( $new_line =~ /^\s*(if|test)/o );
        trim_string($new_line);
        $line = $line . $new_line;
    }

    if ( $line =~ m/$Table_TYPE_PATTERN/o ) {
        my $ret_str = process_table_search( $1, $2 );
        next if $ret_str eq '';
        unless($ret_str eq '') {
		    generateBp($linenum, $ret_str);
		}
    }
    
    return;
}

# only parse return in def_function
sub parse_statement_return {
	my ($line) = @_;
	my $linenum = $.;
	my $new_line = "";
	my $myline = "";

	if ($scope{"def_function"} eq "default") {
		return 0;
	}

	trim_string($line);
	if (index( $line, '(' ) >= 0) {
	    while ( Is_Brace_Match($line) == 0 && ( $new_line = <FILE> ) ) {
			#checkLineNo();
	        next if ( $new_line =~ /^\s*#|^\s*$/o );
	        trim_string($new_line);
	        $line .= $new_line;
	    }
	}

	my $ret_str = process_function_return( 'return', $line, 1);
	unless ($ret_str eq '') {
		generateBp($linenum, $ret_str);
	}

	return 0;
}

#print process_function_return ('return', "cuonter(15)# (hahah)", 1)."\n";
#print process_function_return ('return', "(\"####\")", 1)."\n";
#print process_function_return ('return', "cuonter(15) # (hahah)", 1)."\n";

#exit 0;
sub checkLineNo {
	my $linenum = $.;
	return ;
	if ($linenum == 0) {
		closeFile();
		exit 0;
	} else {
		print "$linenum\n";
	}
}

#-------------------------
# parseCommand
#-------------------------
sub parseCommand {
	my $conf = "";
	p_error("Err0: pls specify the parameter\n -f src_FILE or\n -spa SPA_NAME\n")
		if ( $#ARGV < 1 );

	$conf = "bp.cnf";
	unless ($args{"-spf"} eq '') {
		genBpCnf($conf);
		print "generate genbpN configur file:$conf\n";
		exit 0;
	}

	#get target source file
	$Inputfile = $args{"-f"};
	if ( !$Inputfile ) {
	    $Inputfile = $args{"-spa"};
	
	    p_error("Err1: pls specify the parameter\n -f FILE or\n -spa SPANAME\n")
	      if ( !$Inputfile );
	
	    #open source from $MYNODE src path
	    #print "$MYNODE/sn/sps/$Inputfile/$Inputfile.src";
	    open( FILE, "$MYNODE/sn/sps/$Inputfile/$Inputfile.src" )
	      || p_error("Err: can not open the file $MYNODE/sn/sps/$Inputfile/$Inputfile.src, pls re-check!!\n");
	}
	else {
	
	    #open source from determined path
	    if ( -f "$Inputfile" ) {
	        open( FILE, "$Inputfile" )
	          || p_error("Err: can not open $Inputfile, pls re-check!!\n");
	    }
	    elsif ( -f "./$Inputfile" ) {
	        open( FILE, "./$Inputfile" )
	          || p_error("Err: can not open $Inputfile, pls re-check!!\n");
	    }
	    else {
	        p_error("Err: Can not open $Inputfile, pls re-check!!\n");
	    }
	}

	$Is_EPAY = 1 if ( $Inputfile =~ /EPAY/oi );

	#get BP level
	$BP_LVL = $args{'-l'};
	if ($BP_LVL) {
	    $BP_LVL = 1 if ( $BP_LVL < 1 );
	    $BP_LVL = 3 if ( $BP_LVL > 3 );
	    $BP_Level = $BP_LVL;
	}
	#print "$BP_Level $BP_LVL\n";	
	#get BP bp file path
	$BP_F = $args{'-o'};
	if ( $BP_F && open( OUTPUT, ">$BP_F" ) ) {
	    $BP_File = $BP_F;
	}
	else {
	    $BP_File = "spa.bp";
	    open( OUTPUT, ">$BP_File" )
	      || die "Err: Can not open object bpfile $BP_File\n";
	}
}

sub header {
	my $total = @ALL_BP;
	my $BP_Type = "";
	
	if ( $BP_Level >= 1 ) {
	    $BP_Type = 'TableSearch';
	}
	if ( $BP_Level >= 2 ) {
	    $BP_Type .= ' + FunctionDef';
	}
	if ( $BP_Level >= 3 ) {
	    $BP_Type .= ' + FunctionRet';
	}
	
	#my $c_date = `date`;
	#$c_date =~ tr/\n//d;
	my $c_date = "";
	my $Head = <<EOF
#--------------------------------#
# BP For SRC: $Inputfile
# BP Type   : $BP_Type
# BP Number : $total
# Gen Date  : $c_date
# BP file generated by genbpN 
#--------------------------------#

EOF
  ;

	print OUTPUT $Head;
}

sub commonbp {
	print OUTPUT @ALL_BP;
}

sub extensionBp {
	my $point = 0;

	genLineBp();
	changeGlobal();
	print OUTPUT "detach\n";
}

sub changeGlobal {
	my $var = "";

	foreach $var (@GlobalVar) {
		changeGlobalVarByValue($var, $GlobalVarValue{$var});
	}
}

sub saveGlobalVar {
	my ($var, $val) = @_;
	
	$GlobalVarOpen{$var} = 0;
	$GlobalVarValue{$var} = $val;
}

sub changeGlobalVarByValue {
	my ($var, $val) = @_;
	my $str = "set $var = $val";
	$str = $str;

	if ($GlobalVarOpen{$var} == 1) {
		#print $str."\n";
		print OUTPUT $str."\n";
		return 0;
	} elsif ($GlobalVarOpen{$var} < 0) {
		return 0;
	}

	print "\n[Q:] $GlobalVarTitle{$var}\n";
	print "-----------------------------------------\n";
	print $str."\n";
	print "-----------------------------------------\n";
	print "\n[Y/N, Enter is y]";
	my $answer = <STDIN>;
	if ($answer =~/^\s*$/o || $answer =~ /^\s*(y|Y)/o) {
		#print $str."\n";
		print OUTPUT $str."\n";
	}

	return 0;
}

sub genSkip_FSM_Line {
	push(@FSM_CodePoint, $.);
}

sub judge_Src_Type {
	my ($type) = @_;
	if ($type eq "EPPSA") {
		my $var = "";
		foreach $var (@EPPSAGlbVar) {
			saveGlobalVar($var, $GlobalVarValue{$var});
		}
	} elsif ($type eq "EPAY") {
		my $var = "";
		foreach $var (@EPAYGlbVar) {
			saveGlobalVar($var, $GlobalVarValue{$var});
		}
	}
}

sub genLineBp {
	my $count	= @FSM_CodePoint;
	my $max		= $.;
	my $offset1	= 1;
	my $offset2	= 0;	
	my $idx		= 0;

	if ($count > 1) {
		print "\n[Q:] The line bp in following FSM could be skipped\n";
		print "-----------------------------------------\n";
		print $Skip_FSM_List."\n";
		print "-----------------------------------------\n";
		print "Please make your choice\n";
		print "\n[Y/N, Enter is y]";
		my $answer = <STDIN>;
		if ($answer =~/^\s*$/o || $answer =~ /^\s*(y|Y)/o) {
			while ($idx < $count) {
				$offset1 = $FSM_CodePoint[$idx];
				$offset2 = $FSM_CodePoint[$idx + 1];
				genLineBpByOffset($offset1, $offset2) if $offset2 != '';
				$idx = $idx + 2;
			}
			genLineBpByOffset($FSM_CodePoint[$count-1], $max);
			return
		}
	}

	genLineBpByOffset(1, $max);
}

sub genLineBpByOffset {
	my ($start, $end) = @_;
	my $str = "at $start..$end print(\"at_line: \",\$at_line) end at";
	#print $str."\n";
	print OUTPUT $str."\n";
}

sub tail {
	my $dir_name = dirname($BP_File);
	$dir_name = getcwd if $dir_name eq '.';
	my $totalnum = @ALL_BP;
	my $base_name = basename($BP_File);
	my $Full_BP_File = File::Spec->catfile( $dir_name, $base_name );
	printf("\n Done. Common Total BPs: %d\n", $totalnum);
	my $CMD_OUT = <<EOF
 -----------------------------------------
 You can run fllowing command in debug:spa console:
 source \"$Full_BP_File\"
 -----------------------------------------
 Enjoy it!
EOF
  ;
	print $CMD_OUT;
}


sub loadFile {
	my ($array, $file) = @_;
	unless(open(LOADFILE, "< $file" )) {
		#inf_print("can not open $file!");
		return -1;
	}
	
	@$array = <LOADFILE>;
	close(LOADFILE);	
	return 0;
}

sub checkSkip {
	my ($type) = @_;
	my $str = getScope($type);
	my $linenum = $.;
	
	if ($skip{$str} == 1) {
		push(@CodePoint, $linenum);
	}
}

sub setScope {
	my ($type, $name) = @_;	
	$scope{$type} = $name;
	checkSkip($type);
}

sub resetScope {
	my ($type) = @_;	
	checkSkip($type);
	$scope{$type} = "default";
}

sub getScope {
	my ($type) = @_;
	return $scope{"fsm"}." ".$scope{"state"}." ".$scope{$type};
}

sub printScope {
	my ($type) = @_;
	print $scope{"fsm"}." ".$scope{"state"}." ".$scope{$type};
}


sub saveSkipLineBpFunc {
	my ($type) = @_;
	$type =~ s/\s+/ /g;
	$skip{$type} = 1;
}

sub genBpCnf {
	my ($file) = @_;
	if (-f $file) {
		print "$file exists, check it by yourself.\n";
		return 0;
	}

	unless(open(BP, "> $file")) {
		print "can not open $file";
		return -1;
	}
	my $context = <<EOFBP
# used for genbpN
# version 0.1

# disable function bp
functions = {
	# add function by yourself
	# e.g.  fsm state funcion
}

# changed global variable
globalvars = {
	# add global variable by yourself
	# e.g.   glb_var = 1
}
EOFBP
  ;

	print BP $context;
	close(BP);	
	return 0;
}

sub config {
	my @configuration = ();
	my $position = 0;
	my $line = "";
	return		if (loadFile(\@configuration, "bp.cnf") != 0);
	
	LOOP:for($position = 0; $position < @configuration; $position ++) {
		$line = $configuration[$position];
		#print $line;
		if ($line =~ /^\s*(#.*)?$/o) {
			next LOOP;
		} elsif ($line =~ /^\s*functions\s*=\s*{/o) {
			$position = saveLineScope(\@configuration, $position);
		} elsif ($line =~ /^\s*globalvars\s*=\s*{/o) {
			$position = saveGlobal(\@configuration, $position);
		}
	}
}

sub saveGlobal {
	my ($array, $start) = @_;
	my $position = $start;
	my $line = "";

	#print "[$start] Global\n";
	LOOP:for($position = $start + 1; $position < @$array; $position ++) {
		$line = $$array[$position];
		#print $line;
		if ($line =~ /^\s*(#.*)?$/o) {
			next LOOP;
		} elsif ($line =~ /^\s*([\w!]+)\s*=\s*([\d]+)/o) {
			$position = saveGlobalVar($1, $2);
		} elsif ($line =~ /^\s*}/o) {
			last LOOP;
		}
	}

	return $position;
}

sub saveLineScope {
	my ($array, $start) = @_;
	my $position = $start;
	my $line = "";

	#print "[$start] Line Scope\n";
	LOOP:for($position = $start + 1; $position < @$array; $position ++) {
		$line = $$array[$position];
		#print $line;
		if ($line =~ /^\s*(#.*)?$/o) {
			next;
		} elsif ($line =~ /^\s*([\w!]+\s*[\w!]+\s*[\w!]+)/o) {
			$position = saveSkipLineBpFunc($1);
		} elsif ($line =~ /^\s*}/o) {
			last LOOP;
		}
	}

	return $position;
}

# main
sub main {
	# files will be opened in parseCommand
	parseCommand();
	config();

	parsing();

	# generates bp
	header();
	commonbp();
	extensionBp();
	tail();
	
	closeFile();
}

main();
