#!/bin/sh
######################################################
# usage: ldcase <tid>
# before use, please update:
# 	datadir= 
#	dblistfile= 
#
# author: Liu Hongwei
######################################################

datadir=/u/ainet/hongwehl/dest
dblistfile=/u/ainet/hongwehl/dbdata/rtdb.list

if [ $# = 0 ]
then
	echo "usage: ldcase <tid>"
	exit 1
fi

if [ ! -d $datadir ]
then
	echo "error: data dir $datadir does not exist!"
	exit 1
fi

tid=$1

if [ -f $dblistfile ]
then
	dblist=`cat $dblistfile`		
else
	dblist=`psql -Uscncraft -At -c "select * from rtdb_app where db_name not in ('NDB', 'BDB', 'HLRV', 'HLRNV')"` 
fi

for db in $dblist
do
	dbfile="$datadir/$tid.$db"
	if [ -f $dbfile ]
	then
		echo "loading $dbfile"
		#ldb $db $dbfile
		eval /cs/sn/cr/cepexec LOAD_DB \'LOAD:DB=$db,FILE=\"$dbfile\",UCL\'
		if [ $? = 0 ]
		then
        		echo "load $DBNAME success"
		else
        		echo "load $DBNAME fail"
		fi
	fi
done
