#!/bin/sh

#################################################
# This is frm loader on ATCA
# Usage: ldfrm <name>.frm | <name>.frmbk 
#
# Note: when loading frmbk, it will load file conversely
#	and clear rcdata in PSQL
#
# Liu Hongwei <hong_wei.hl.liu@alcatel-lucent.com>
# 2014/12/18
# 2016/04/18    updated, fix some bugs
#################################################

FRMFILE=$1
fulllink=`readlink -f $FRMFILE`
FILENAME=`basename $FRMFILE`
FRMFILETMP=/tmp/$FILENAME.tmp
cat $FRMFILE |sed -e "s/! /,/g" > $FRMFILETMP

isFrmbk=`echo $FRMFILE | egrep '.frmbk'`
if [ ! -z "$isFrmbk" ]
then
	#echo "$FRMFILE is a .frmbk file"
	tac $FRMFILE |sed -e "s/! /,/g" > $FRMFILETMP
fi

echo -e "END;" >> $FRMFILETMP
/cs/sn/cr/cepexec RCV_TEXT "RCV:TEXT,SPA" <$FRMFILETMP

#tracked=`psql -Uscncraft -At -c "select tablename from pg_tables where tablename='rcdata'"`
#if [ ! -z "$tracked" ] && [ ! -z "$isFrmbk" ]
#if [ ! -z "$tracked" ]
#then
#       echo "Clear rcdata"
#       psql -Uscncraft -c "truncate table rcdata"
#fi

rm $FRMFILETMP
