#!/bin/sh
# this is a new LogCMB, which is faster than old one, the more tmp log there are, the more faster
#
#   Liu Hongwei
#   2017/06/23

LOGFILE=$1
if [ -z $LOGFILE ] || [ ! -f $LOGFILE ]
then
    echo "usage: cmblog <logfile>"
    exit 1
fi

################################################
# generate a script to get log from other blade

getLogScript=/tmp/gettmplog
if [ ! -f $getLogScript ]
then
    cat <<!END >$getLogScript
#!/bin/sh

USER=ainet
PASSWD=ainet1
logloc=\$1

logname=\`basename \$logloc\`
blade=\`echo \$logloc |awk -F\. '{print \$3}'\`

/usr/bin/expect -c "
    set timeout 5
    spawn /usr/bin/sftp \${USER}@\${blade}
    expect \"*?assword:*\"
    send -- \\"\${PASSWD}\\r\\"
    expect \\"sftp*\\"
    send -- \\"get \${logloc} /tmp\\r\\"
    expect \\"sftp*\\"
    send -- \\"rm \${logloc}\\r\\"
    expect \\"sftp*\\"
    send -- \\"bye\\r\\"
    expect eof" >/dev/null
!END
    chmod 755 $getLogScript
fi

tmp_log=$LOGNAME.tmp
>$tmp_log

gawk -v getLogScript=$getLogScript -v tmp_cmb_log=$tmp_log '
BEGIN{
    RS="\n\001\n";
    ORS="\n\001\n"
}

/\/sn\/log\/CRmsg/{
    match($0, /\/sn\/log\/CRmsg.*\.0-0-[0-9]+/)
    logloc = substr($0, RSTART, RLENGTH)
    split(logloc, t, "/")
    logname = t[5]
    system(getLogScript " " logloc)

    tmplogname = "/tmp/"logname
    if (system("test -f " tmplogname)) {
        print logname "not exist"
        next
    }
    printf("Restoring from %s\n", logname)
    while (getline line <tmplogname) {
        print line >tmp_cmb_log
    }
    system("rm " tmplogname)
}

!/\/sn\/log\/CRmsg/{
    print >tmp_cmb_log
}
' $LOGFILE # >>$tmp_log

mv $tmp_log $LOGFILE

