#!/bin/ksh

# the script name
ME=`basename $0`

# pre-defined parameter
USER="ainet"
PASSWD="ainet1"
KEYWORD="/sn/log/CRmsg"

function usage {
cat <<!

Usage: $ME logname

$ME used to resotre the tmp log like 'Log large OM in file '/sn/log/CRmsg/EPAY27A_2.tmp4.0-0-2' in blade' to a complete one
!
exit 1
}

# Main Start
if [ $# -ne 1 ]
then
    usage
fi

if [ ! -f $1 ]
then
    echo "$1 is not a valide file"
    exit
fi

cd `dirname $1`
log=`basename $1`

while grep $KEYWORD $log >/dev/null 2>&1
do
    logloc=`grep $KEYWORD $log | head -n 1 |awk -F\' '{print $2}'`
    logname=`basename $logloc`
    blade=`echo $logloc |awk -F\. '{print $3}'`

    echo "Restoring $logname to $log.."
    # get the tmp log from other blade
    /usr/bin/expect -c " 
    set timeout 5
    spawn /usr/bin/sftp ${USER}@${blade}
    expect \"*?assword:*\"
    send -- \"${PASSWD}\r\"
    expect \"sftp*\"
    send -- \"get ${logloc} /tmp\r\"
    expect \"sftp*\"
    send -- \"rm ${logloc}\r\"
    expect \"sftp*\"
    send -- \"bye\r\"
    expect eof" >/dev/null
    #/usr/bin/expect -c "spawn scp ${USER}@${blade}:${logloc} /tmp
    #    expect \"*?assword:*\"
    #    send -- \"${PASSWD}\r\"
    #    expect eof" >/dev/null

    # restore the tmp log to the original location
    gawk 'BEGIN{RS="\n\001\n"; ORS="\n\001\n"} '"/${logname}/"'{while (getline d <"/tmp/'"${logname}"'") print d} '"!/${logname}/"'{print}' $log >$log.tmp
    mv $log.tmp $log
    rm /tmp/${logname}
done

echo "Done!!"
