#!/bin/sh
###########################################################
# name: ngini
# usage: ngini
# description:
#       this script is for user to send CCRi in terminal by 
#       command, no need copy cep cmd to subshl
#       before using this script, need:
#       1) update CCR_INDEX to the CCRi index you are using
#       2) update DIAMCL version and table name in ngin.frm
#       3) update RK here to the rk you are using in DIAMCL
#
# author: Liu Hongwei
#         hong_wei.hl.liu@alcatel-lucent.com
###########################################################

CCR_INDEX=UK01
#CCR_INDEX=396
CEPEXEC="/sn/cr/cepexec"
BASEFRM="/u/ainet/hongwehl/bin/ngin.frm"
CC_NUM=1
CC_NUM_COUNTER="/tmp/NGIN_CC_NUM_COUNTER"

#if [ -f $CC_NUM_COUNTER ]
#then
#	mv $CC_NUM_COUNTER $CC_NUM_COUNTER.old
#fi

$CEPEXEC RCV_TEXT "RCV:TEXT,SPA" < $BASEFRM
$CEPEXEC SEND_TEXT "snd:text=\"CCR:$CCR_INDEX\",RK=\"diam_key\""
echo -e "\nSend CCRi:$CCR_INDEX, cc_request_number = $CC_NUM\n"

CC_NUM=$(($CC_NUM + 1))
echo $CC_NUM > $CC_NUM_COUNTER
