#!/bin/sh
ROOT_PASSWD="r00t"
CEPEXEC="/sn/cr/cepexec"

username=`whoami`
if [ $username = "root" ]
then
	/opt/config/bin/PlatformSync all /cs/sn/bill
else
	/usr/bin/expect -c "
		spawn su -
		expect {
		"*assword:" {
			send \"$ROOT_PASSWD\n\" 
			expect \"*root-#\"
			send \"/opt/config/bin/PlatformSync all /cs/sn/bill\n\"
			expect \"*root-#\"
		}
	}
	"
	echo
fi

$CEPEXEC SET_AMA "SET:AMA,INTERMED=1min"
$CEPEXEC SET_AMA "SET:AMA,FILTER=OFF"
$CEPEXEC SET_AMA "SET:AMA,FILTER=ON"

for blade in `echo "0-0-1 0-0-9"`
do
	$CEPEXEC INIT_PROC "INIT:PROC=BILL,LEVEL=1,MACHINE=$blade,UCL"
done

for blade in `ls /opt/config/servers/`
do
	$CEPEXEC INIT_PROC "INIT:PROC=BILLHPR,LEVEL=1,MACHINE=$blade,UCL"
done
