#!/bin/sh

mcas_host="135.242.106.103"
display="135.252.17.202:1.0"

p250alu="135.252.170.143"
mgts_user="hongwehl"
mgts_passwd="hongwehl"
assign_name="ITU_SSP201_SCP309_VFDE"
state_name="CML2_SHORT_CODE_RCHG"
timer=15

MGTS_DATA=/home/catapult/USERS/$mgts_user/datafiles

/usr/bin/expect -c "
	set timeout 60

	spawn telnet $p250alu
	expect "*login:" {
		send \"$mgts_user\n\"
		expect {
		"*assword:" {
			send \"$mgts_passwd\n\"
			expect \"*$mgts_user> \"
			send \"setenv MGTS_CLIENT /home/MGTS/17.1/MGTS\n\"
			expect \"*$mgts_user> \"
			send \"setenv OS_TYPE Linux\n\"
			expect \"*$mgts_user> \"
			send \"setenv DISPLAY $display\n\"
			expect \"*$mgts_user> \"

			send \"source /home/catapult/USERS/$mgts_user/mgts_cit_csh\n\"
			expect \"*$mgts_user> \"
			send \"setenv MGTS_DATA /home/catapult/USERS/$mgts_user/datafiles\n\"
			expect \"*$mgts_user> \"
			send \"/home/MGTS/17.1/MGTS/scripts/stop_mgts_script\n\"
			expect \"*$mgts_user> \"
			send \"/home/MGTS/17.1/MGTS/bin/run_mgts_script\n\"
			expect \"*$mgts_user> \"
			send \"/home/MGTS/17.1/MGTS/bin/shelfConnect EE\n\"
			expect \"*$mgts_user> \"
			send \"/home/hongwehl/vmware/passThru -mgtshost p250alu $mcas_host -debug >/dev/null &\n\"
			expect \"*$mgts_user> \"
	
			send \"cd /home/catapult/USERS/$mgts_user/datafiles\n\"
			expect \"*datafiles> \"

			send \"networkExecute $assign_name -download\n\"
			expect \"*datafiles> \"

			send \"shelfPASM EE -node SSP -machine \\\"$state_name State Machine\\\" -run -log $MGTS_DATA/$state_name.mgts.runlog\n\"
			expect \"*datafiles> \"

			send \"sleep $timer\n\"
			expect \"*datafiles> \"

			send \"pkill -u $mgts_user passThru\n\"
			expect \"*datafiles> \"

			send \"/home/MGTS/17.1/MGTS/scripts/stop_mgts_script\n\"
			expect \"*datafiles> \"
			}
		}
	}
"
echo
