#!/bin/sh
# configure message

session_id="SI;12345678;12340001"
ccri=11
ccru=12
ccrt=13

# msisdn sgsn station_id
para_vfi=(393470999107 "010130037004" "lte.vodafone.it")
para_vfuk=(447469979955 "212183144242" "pp.vodafone.co.uk")
para_vfgr=(306944900340 "213249062000" "internet.vodafone.gr")
para_vfie=(353870999127 "213233130056" "hs.vodafone.ie")

# please specify customer in variable "para"
para=(${para_vfi[@]})

msisdn=${para[0]}
sgsn=${para[1]}
station_id=${para[2]}

form_msg=$(psql -Uscncraft -At -c "select item from rcmenutbl where title='client global rc table CCR_Message_Variable_Tbl' limit 1")
form_sub=$(psql -Uscncraft -At -c "select item from rcmenutbl where title='client global rc table CCR_Subscription_Id_Tbl' limit 1")

echo "CR_Message_Variable_Tbl: $form_msg"
echo "CCR_Subscription_Id_Tbl: $form_sub"
echo "FORM=$form_sub&CHG,index=\"1\",Sub_Value=\"$msisdn\",CHG!" >/tmp/msg.frm

for idx in $ccri $ccru $ccrt
do
cat <<!eof >>/tmp/msg.frm
FORM=$form_msg&CHG,index="$idx",CCR_Session_ID="$session_id",CCR_Dcca_Vendor_Specific_Avps_Bound.called_station_id="$station_id",CCR_Dcca_Vendor_Specific_Avps_Bound.sgsn_address="$sgsn",CHG!
!eof
done

echo -e "please run:\n\tldfrm /tmp/msg.frm"
