#!/bin/sh
# this script is to specify diameter usu
# so that it is easier to run different cases with different msisdn
# currently, it can only support one diameter client, e.g.
# 	DIAMCL29B, DIAMCL173 can't be installed on same machine at same time
#
#	Liu Hongwei
#	2018.7.31
#       2018.8.29    extended to support both time and volume

if [ $# -eq 0 ]
then
    echo "change diameter usu: usu -i <usu index> -t <time> -v <volume>"
    exit 1
fi

while getopts i:t:v: option
do
    case $option in
    i)  
        index="$OPTARG"
        ;;  
    t)
        tm="$OPTARG"
        ;;
    v)
        vol="$OPTARG"
        ;;
    \?) 
        echo "can't handle option $option" >&2
        ;;  
    esac
done

if [ -z "$index" ]
then
    echo "please specify index, usage: usu -i <usu index> -t <time> -v <volume>"
    exit 1
fi

str=""
if [ ! -z "$tm" ]
then
    is_digit=$(echo $tm | grep "[^0-9]")
    if [ ! -z "$is_digit" ]
    then
         echo "time $tm is not number"
         exit 1
    else
         str="CC_Time=\"$tm\""
    fi
fi
if [ ! -z "$vol" ]
then
    is_digit=$(echo $vol | grep "[^0-9]")
    if [ ! -z "$is_digit" ]
    then
        echo "vol $vol is not number"
        exit 1
    else
        if [ ! -z "$str" ]
        then
            str=$str","
        fi
        str=$str"CC_Total_Octets=\"$vol\""
    fi
fi

tmpfrm="/tmp/change_diam_usu.frm"
diamcl=$(psql -Uscncraft -At -c "select span from spa_tbl where span like 'DIAMCL%' limit 1")
usu_tbl=$(psql -Uscncraft -At -c "select item from rcmenutbl where title='client global rc table Used_Service_Unit_Tbl' and parent='$diamcl'")
#usu_tbl="SPA_DIAMCL29J_12"

if [ -z "$str" ]
then
    echo "both time and volue are not specified, nothing to change"
    exit 0
fi

cat <<!eof >$tmpfrm
FORM=$usu_tbl&CHG,index="$index",$str,CHG!
!eof

ldfrm $tmpfrm
echo "change usu time=$tm, volume=$vol, empty means no change"
rm $tmpfrm

